### ISSUE TITLE
About dcls_functional.py

### ISSUE THREAD

**Issue by lishuyaah** [K-H-Ismail/Dilated-Convolution-with-Learnable-Spacings-PyTorch#1]
Hello, I would like to ask why dcls_construct_1d documents can not be read in, has been marked in red. Hope to get a reply, thank you！

**Comment by K-H-Ismail** [comment]
Hello,
To compile DCLS you need to do:

```bash
git clone https://github.com/K-H-Ismail/Dilated-Convolution-with-Learnable-Spacings-PyTorch.git
cd Dilated-Convolution-with-Learnable-Spacings-PyTorch
git pull
python ./setup.py install --user
``` 
Make sure that your cuda home is set before compiling, if it is not please set it as follows ```  export CUDA_HOME=/usr/local/cuda```

If the compilation is done successfully, you can use DCLS1d as follows:
```python
import torch
from DCLS.construct.modules.Dcls import  Dcls1d 

# Will construct kernels of size 7x7 with 3 elements inside each kernel
m = Dcls1d(3, 16, kernel_count=3, dilated_kernel_size=7).cuda()
input = torch.rand(8, 3, 32).cuda()
output = m(input)
loss = output.sum()
loss.backward()
print(output, m.weight.grad, m.P.grad)
```

We have slightly changed the signatures of functions and this is how we can use Dcls now.

Tell me if this works for you, if not please reply to this message by the error text it gives you.

**Comment by K-H-Ismail** [comment]
Hello,
I have fixed the import error you probably get in dcls construct. It was due to the use of another library [depthwise_conv2d_implicit_gemm](https://github.com/MegEngine/cutlass/tree/master/examples/19_large_depthwise_conv2d_torch_extension). You can now just pull the new version of DCLS and recompile by doing 
```bash
cd Dilated-Convolution-with-Learnable-Spacings-PyTorch
git pull
python ./setup.py install --user
 ```

Sorry for the inconvenience.
