### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by Lutong-Qin** [K-H-Ismail/Dilated-Convolution-with-Learnable-Spacings-PyTorch#2]
![image](https://user-images.githubusercontent.com/51037385/200461406-29994b71-b099-4c92-a510-89a5be96a430.png)
cannot import name '_reverse_repeat_tuple' from 'torch.nn.modules.utils' (/data1/lib/python3.8/site-packages/torch/nn/modules/utils.py)
My torch vision 1.12.1,How can I solve it?Thank you very much.

**Comment by K-H-Ismail** [comment]
Hello,
I tried it using 1.12.1, seems to work for me. as you can see it is available in the official pytorch code https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/utils.py
the two lines that did not work for you are
```python3
from torch.nn.modules.utils import _single, _pair, _triple, _reverse_repeat_tuple
from torch.nn.common_types import _size_1_t, _size_2_t, _size_3_t
```
Are you sure about your torch version ?
can you do
```python
import torch
print(torch.__version__)
```

**Comment by Lutong-Qin** [comment]
I forgot to reply to help you. I'm really sorry. Thank you very much for your answer. Thank you.

**Comment by K-H-Ismail** [comment]
No problem. I hope you find this useful.
